### ISSUE TITLE
failed to build angular project which using jalali-moment package

### ISSUE THREAD

**Issue by behzadjj** [fingerpich/jalali-moment#51]
Once i use this package in an angular project and run build command it show error as follow: 

BUILD ERROR
Cannot call a namespace ('moment')
Error: Cannot call a namespace ('moment')
    at error (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:199:15)
    at Module.error (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:17170:9)
    at CallExpression.bind (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:14725:30)
    at MemberExpression$$1.NodeBase.bind (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:13499:23)
    at MemberExpression$$1.bind (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:15672:35)
    at CallExpression.NodeBase.bind (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:13499:23)
    at CallExpression.bind (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:14721:31)
    at AssignmentExpression.NodeBase.bind (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:13499:23)
    at AssignmentExpression.bind (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:14605:31)
    at ExpressionStatement$$1.NodeBase.bind (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:13499:23)

Cannot call a namespace ('moment')
Error: Cannot call a namespace ('moment')
    at error (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:199:15)
    at Module.error (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:17170:9)
    at CallExpression.bind (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:14725:30)
    at MemberExpression$$1.NodeBase.bind (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:13499:23)
    at MemberExpression$$1.bind (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:15672:35)
    at CallExpression.NodeBase.bind (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:13499:23)
    at CallExpression.bind (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:14721:31)
    at AssignmentExpression.NodeBase.bind (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:13499:23)
    at AssignmentExpression.bind (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:14605:31)
    at ExpressionStatement$$1.NodeBase.bind (D:\angular-pro\libraries\node_modules\rollup\dist\rollup.js:13499:23)

Date adapter want to use jalali moment in angular material date picker.
1.I run an angular project with : `ng new my-app`
2.Then import jalali moment package
3.Create an adapter for date.

Guide for using this adapter can found in : [jalali-date-picker](http://roojan.ir/287457/%D8%A2%D9%85%D9%88%D8%B2%D8%B4-%E2%80%AB%D8%B4%D9%85%D8%B3%DB%8C-%D8%B3%D8%A7%D8%B2%DB%8C-date-picker-%D8%AA%D9%88%DA%A9%D8%A7%D8%B1-angular-material-6x)  

Where is the problem?

**Comment by fingerpich** [comment]
duplicate with #50

**Comment by fingerpich** [comment]
has helped you?
